replicaCount: 1

fullnameOverride: orchestrator

image:
  repository: telefrek/lucent-orchestrator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

cors: []

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: 
  limits:
   memory: 1Gi
   cpu: 1
  requests:
   memory: 256Mi
   cpu: .25

content:
  path: '/opt/lucent/adcontents'

hostAlias: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpression:
          - key: component
            operator: In
            values:
            - orchestrator
        topologyKey: kubernetes.io/hostname
