using Lucent.Common.Exchanges;
using Lucent.Common.OpenRTB;

namespace Lucent.Common.Bidding
{
    /// <summary>
    /// Class to manipulate bid macros
    /// </summary>
    public class BidMacros
    {
        /// <summary>
        /// Static collection of supported macros
        /// </summary>
        /// <value></value>
        public static readonly string[] MACROS = new string[]{
            "{adv_id}", // ID of advertiser for the offer
            "{click_id}", // Publisher click ID specified in the tracking link
            "{pub_id}", // ID/name of app or website
            "{exc_id}", // ID/name of exchange
            "{city}", // City name where the click came from
            "{country_code}", // User’s ISO two-letter country code based on IP address (ex: US, UK)
            "{currency}", // Three-letter ISO currency abbreviation (ex: USD, EUR)
            "{date}", // Current date formatted as YYYY-MM-DD
            "{datetime}", // Current date and time formatted as YYYY-MM-DD HH:MM:SS
            "{time}", // Current time formatted as HH:MM:SS
            "{ip}", // IP address that started the click session
            "{carrier}", // Name of user’s mobile carrier
            "{payout}", // Offer payout from advertiser to us
            "{purchase}", // Value of a customer’s purchase
            "{conversion_id}", // ID of the event (a unique # for install, purchase etc)
            "{event}", // Name of the event (example: Install)
            "{device_brand}", // Brand name of user’s device from user agent string (example: Apple)
            "{device_model}", // Model name of user’s device from user agent string (example: iPhone)
            "{device_os}", // OS name of user’s device from user agent string (example: iOS)
            "{device_os_version}", // OS version of user’s device from user agent string (example: 4.3.2)
            "{google_aid}", // Google Android advertising identifier used to attribute clicks to installs for apps in the Google Play store
            "{android_id}", // Unique ID for Android device
            "{idfa}", // Apple iOS advertising identifier (iOS 6+)
            "{unid}", // Catch-all for unknown mobile device identifiers
            "{user_id}", // Application-specific user ID (generated by app developer)
            "{creative_id}", // ID of creative
            "{creative_group}", // id or name of a set of creatives
        };
    }
}